vpath %_read1.fastq.gz /data
vpath %_read2.fastq.gz /data

TARGETS=                                                                   \
GA_24_15173_CGATGT.co.gz                                                   \
GA_24_15173_GTTCAC.co.gz                                                   \
GA_24_15173_TCTTAG.co.gz                                                   \
GA_24_15173_TGCAGT.co.gz                                                   \
GA_24c_15171_AGCTTG.co.gz                                                  \
GA_24c_15171_GCCAAG.co.gz                                                  \
GA_24c_15171_TGACCA.co.gz                                                  \
GA_24c_15171_TTAGGC.co.gz                                                  \
GA_48_15174_CTTGTA.co.gz                                                   \
GA_48_15174_GCTGAA.co.gz                                                   \
GA_48_15174_GGCTAC.co.gz                                                   \
GA_48_15174_TAGCTT.co.gz                                                   \
GA_48c_15172_ACAGTG.co.gz                                                  \
GA_48c_15172_ACTTGA.co.gz                                                  \
GA_48c_15172_ATGTCT.co.gz                                                  \
GA_48c_15172_GATCAG.co.gz                                                  \
GA_48c_15172_TCTACA.co.gz                                                  \
GT_24_15432_CGATGT.co.gz                                                   \
GT_24_15432_GTTCAC.co.gz                                                   \
GT_24_15432_TCTTAG.co.gz                                                   \
GT_24_15432_TGCAGT.co.gz                                                   \
GT_24c_15430_AGCTTG.co.gz                                                  \
GT_24c_15430_GCCAAG.co.gz                                                  \
GT_24c_15430_TGACCA.co.gz                                                  \
GT_24c_15430_TTAGGC.co.gz                                                  \
GT_48_15433_CTTGTA.co.gz                                                   \
GT_48_15433_GCTGAA.co.gz                                                   \
GT_48_15433_GGCTAC.co.gz                                                   \
GT_48_15433_TAGCTT.co.gz                                                   \
GT_48c_15431_ACAGTG.co.gz                                                  \
GT_48c_15431_ACTTGA.co.gz                                                  \
GT_48c_15431_ATGTCT.co.gz                                                  \
GT_48c_15431_GATCAG.co.gz                                                  \
CA_24_15639_CGATGT.co.gz                                                   \
CA_24_15639_GTTCAC.co.gz                                                   \
CA_24_15639_TCTTAG.co.gz                                                   \
CA_24_15639_TGCAGT.co.gz                                                   \
CA_24c_15637_AGCTTG.co.gz                                                  \
CA_24c_15637_GCCAAG.co.gz                                                  \
CA_24c_15637_TGACCA.co.gz                                                  \
CA_24c_15637_TTAGGC.co.gz                                                  \
CA_48_15640_CTTGTA.co.gz                                                   \
CA_48_15640_GCTGAA.co.gz                                                   \
CA_48_15640_GGCTAC.co.gz                                                   \
CA_48_15640_TAGCTT.co.gz                                                   \
CA_48c_15638_ACAGTG.co.gz                                                  \
CA_48c_15638_ACTTGA.co.gz                                                  \
CA_48c_15638_ATGTCT.co.gz                                                  \
CA_48c_15638_GATCAG.co.gz                                                  \
GTLa_24_15479_CGATGT.co.gz                                                 \
GTLa_24_15479_GTTCAC.co.gz                                                 \
GTLa_24_15479_TCTTAG.co.gz                                                 \
GTLa_24_15479_TGCAGT.co.gz                                                 \
GTLa_24c_15477_AGCTTG.co.gz                                                \
GTLa_24c_15477_GCCAAG.co.gz                                                \
GTLa_24c_15477_TGACCA.co.gz                                                \
GTLa_24c_15477_TTAGGC.co.gz                                                \
GTLa_48_15480_CTTGTA.co.gz                                                 \
GTLa_48_15480_GCTGAA.co.gz                                                 \
GTLa_48_15480_GGCTAC.co.gz                                                 \
GTLa_48_15480_TAGCTT.co.gz                                                 \
GTLa_48c_15478_ACAGTG.co.gz                                                \
GTLa_48c_15478_ACTTGA.co.gz                                                \
GTLa_48c_15478_ATGTCT.co.gz                                                \
GTLa_48c_15478_GATCAG.co.gz                                                \
CAla_24_15643_CGATGT.co.gz                                                 \
CAla_24_15643_GTTCAC.co.gz                                                 \
CAla_24_15643_TCTTAG.co.gz                                                 \
CAla_24_15643_TGCAGT.co.gz                                                 \
CAla_24c_15641_AGCTTG.co.gz                                                \
CAla_24c_15641_GCCAAG.co.gz                                                \
CAla_24c_15641_TGACCA.co.gz                                                \
CAla_24c_15641_TTAGGC.co.gz                                                \
CAla_48_15644_CTTGTA.co.gz                                                 \
CAla_48_15644_GCTGAA.co.gz                                                 \
CAla_48_15644_GGCTAC.co.gz                                                 \
CAla_48_15644_TAGCTT.co.gz                                                 \
CAla_48c_15642_ACAGTG.co.gz                                                \
CAla_48c_15642_ACTTGA.co.gz                                                \
CAla_48c_15642_ATGTCT.co.gz                                                \
CAla_48c_15642_GATCAG.co.gz                                                \
GAn_la_24_20465_AGCTTG.co.gz                                               \
GAn_la_24_20465_CGATGT.co.gz                                               \
GAn_la_24_20465_TCTTAG.co.gz                                               \
GAn_la_24_20465_TGCAGT.co.gz                                               \
GAn_la_48_20466_ATGTCT.co.gz                                               \
GAn_la_48_20466_GCCAAG.co.gz                                               \
GAn_la_48_20466_GTTCAC.co.gz                                               \
GAn_la_48_20466_TTAGGC.co.gz                                               \
GAn_la_c_20464_CTGGAT.co.gz                                                \
GAn_la_c_20464_GCTGAA.co.gz                                                \
GAn_la_c_20464_TAGGAC.co.gz                                                \
GAn_la_c_20464_TCTACA.co.gz                                                \
24_13073_GCCAAG.co.gz                                                      \
24_13073_GTTCAC.co.gz                                                      \
24_13073_TCTTAG.co.gz                                                      \
24_13073_TGCAGT.co.gz                                                      \
48_13074_ATGTCT.co.gz                                                      \
48_13074_GCTGAA.co.gz                                                      \
48_13074_TAGGAC.co.gz                                                      \
48_13074_TCTACA.co.gz                                                      \
con_13072_AGCTTG.co.gz                                                     \
con_13072_CGATGT.co.gz                                                     \
con_13072_CTGGAT.co.gz                                                     \
con_13072_TTAGGC.co.gz                                                     \
LA_24_13508_AGCTTG.co.gz                                                   \
LA_24_13508_CGATGT.co.gz                                                   \
LA_24_13508_TCTTAG.co.gz                                                   \
LA_24_13508_TGCAGT.co.gz                                                   \
LA_48_13509_ATGTCT.co.gz                                                   \
LA_48_13509_GCCAAG.co.gz                                                   \
LA_48_13509_GTTCAC.co.gz                                                   \
LA_48_13509_TTAGGC.co.gz                                                   \
LA_c_13507_CTGGAT.co.gz                                                    \
LA_c_13507_GCTGAA.co.gz                                                    \
LA_c_13507_TAGGAC.co.gz                                                    \
LA_c_13507_TCTACA.co.gz                                                    \
Gala_24_15624_CGATGT.co.gz                                                 \
Gala_24_15624_GTTCAC.co.gz                                                 \
Gala_24_15624_TCTTAG.co.gz                                                 \
Gala_24_15624_TGCAGT.co.gz                                                 \
Gala_24c_15622_AGCTTG.co.gz                                                \
Gala_24c_15622_GCCAAG.co.gz                                                \
Gala_24c_15622_TGACCA.co.gz                                                \
Gala_24c_15622_TTAGGC.co.gz                                                \
Gala_48_15625_CTTGTA.co.gz                                                 \
Gala_48_15625_GCTGAA.co.gz                                                 \
Gala_48_15625_GGCTAC.co.gz                                                 \
Gala_48_15625_TAGCTT.co.gz                                                 \
Gala_48c_15623_ACAGTG.co.gz                                                \
Gala_48c_15623_ACTTGA.co.gz                                                \
Gala_48c_15623_ATGTCT.co.gz                                                \
Gala_48c_15623_GATCAG.co.gz                                                \
Gala_48c_15623_GATCAG.co.gz                                                \
24_34998_ACAGTG.co.gz                                                      \
24_34998_GTTCAC.co.gz                                                      \
24_34998_TCTTAG.co.gz                                                      \
24_34998_TGCAGT.co.gz                                                      \
48_34999_ATGTCT.co.gz                                                      \
48_34999_GCTGAA.co.gz                                                      \
48_34999_TAGGAC.co.gz                                                      \
48_34999_TCTACA.co.gz                                                      \
r1r2_34997_AGCTTG.co.gz                                                    \
r1r2_34997_CGATGT.co.gz                                                    \
r1r2_34997_CTGGAT.co.gz                                                    \
r1r2_34997_TTAGGC.co.gz                                                    \
24_35175_ACAGTG.co.gz                                                      \
24_35175_GTTCAC.co.gz                                                      \
24_35175_TCTTAG.co.gz                                                      \
24_35175_TGCAGT.co.gz                                                      \
48_35176_ATGTCT.co.gz                                                      \
48_35176_GCTGAA.co.gz                                                      \
48_35176_TAGGAC.co.gz                                                      \
48_35176_TCTACA.co.gz                                                      \
R1R2_35174_AGCTTG.co.gz                                                    \
R1R2_35174_CGATGT.co.gz                                                    \
R1R2_35174_CTGGAT.co.gz                                                    \
R1R2_35174_TTAGGC.co.gz                                                    \
48PV_1_lib_00283AAA_TCTACA.co.gz                                           \
48PV_2_lib_00284AAA_GCTGAA.co.gz                                           \
48PV_3_lib_00285AAA_TAGGAC.co.gz                                           \
48PV_lib_00282AAA_ATGTCT.co.gz

# Manually flagged as bad profiles from clustering analyses.
BAD=                                                                       \
Gala_48c_15623_GATCAG                                                      \
Gala_48c_15623_ACTTGA                                                      \
Gala_24c_15622_GCCAAG                                                      \
CA_48c_15638_ACAGTG                                                        \
CA_48_15640_TAGCTT                                                         \
CA_48_15640_GCTGAA

CONTROLS=                                                                  \
GA_24c_15171_AGCTTG                                                        \
GA_24c_15171_GCCAAG                                                        \
GA_24c_15171_TGACCA                                                        \
GA_24c_15171_TTAGGC                                                        \
GA_48c_15172_ACAGTG                                                        \
GA_48c_15172_ACTTGA                                                        \
GA_48c_15172_ATGTCT                                                        \
GA_48c_15172_GATCAG                                                        \
GA_48c_15172_TCTACA                                                        \
GT_24c_15430_AGCTTG                                                        \
GT_24c_15430_GCCAAG                                                        \
GT_24c_15430_TGACCA                                                        \
GT_24c_15430_TTAGGC                                                        \
GT_48c_15431_ACAGTG                                                        \
GT_48c_15431_ACTTGA                                                        \
GT_48c_15431_ATGTCT                                                        \
GT_48c_15431_GATCAG                                                        \
CA_24c_15637_AGCTTG                                                        \
CA_24c_15637_GCCAAG                                                        \
CA_24c_15637_TGACCA                                                        \
CA_24c_15637_TTAGGC                                                        \
CA_48c_15638_ACTTGA                                                        \
CA_48c_15638_ATGTCT                                                        \
CA_48c_15638_GATCAG                                                        \
GTLa_24c_15477_AGCTTG                                                      \
GTLa_24c_15477_GCCAAG                                                      \
GTLa_24c_15477_TGACCA                                                      \
GTLa_24c_15477_TTAGGC                                                      \
GTLa_48c_15478_ACAGTG                                                      \
GTLa_48c_15478_ACTTGA                                                      \
GTLa_48c_15478_ATGTCT                                                      \
GTLa_48c_15478_GATCAG                                                      \
CAla_24c_15641_AGCTTG                                                      \
CAla_24c_15641_GCCAAG                                                      \
CAla_24c_15641_TGACCA                                                      \
CAla_24c_15641_TTAGGC                                                      \
CAla_48c_15642_ACAGTG                                                      \
CAla_48c_15642_ACTTGA                                                      \
CAla_48c_15642_ATGTCT                                                      \
CAla_48c_15642_GATCAG                                                      \
GAn_la_c_20464_CTGGAT                                                      \
GAn_la_c_20464_GCTGAA                                                      \
GAn_la_c_20464_TAGGAC                                                      \
GAn_la_c_20464_TCTACA                                                      \
con_13072_AGCTTG                                                           \
con_13072_CGATGT                                                           \
con_13072_CTGGAT                                                           \
con_13072_TTAGGC                                                           \
LA_c_13507_CTGGAT                                                          \
LA_c_13507_GCTGAA                                                          \
LA_c_13507_TAGGAC                                                          \
LA_c_13507_TCTACA                                                          \
Gala_24c_15622_AGCTTG                                                      \
Gala_24c_15622_TGACCA                                                      \
Gala_24c_15622_TTAGGC                                                      \
Gala_48c_15623_ACAGTG                                                      \
Gala_48c_15623_ATGTCT                                                      \
r1r2_34997_AGCTTG                                                          \
r1r2_34997_CGATGT                                                          \
r1r2_34997_CTGGAT                                                          \
r1r2_34997_TTAGGC                                                          \
R1R2_35174_AGCTTG                                                          \
R1R2_35174_CGATGT                                                          \
R1R2_35174_CTGGAT                                                          \
R1R2_35174_TTAGGC                                                          

all: $(TARGETS)

%.pps: %_read1.fastq.gz %_read2.fastq.gz
	python preprocess.py $^ > $@

%.stc: %.pps
	cut -f1 $< | starcode -d2 --print-clusters > $@

%.co.gz: %.pps %.stc
	python count.py $^ $*_seq.txt | gzip > $@ && rm $^ && gzip $*_seq.txt

rmbad:
	rm -f $(addsuffix *, $(BAD))

mvctrl:
	mv $(addsuffix *, $(CONTROLS)) controls/

clean:
	rm -rf *.pps *.co.gz
