vpath %_read1.fastq.gz /data
vpath %_read2.fastq.gz /data

TARGETS=                                                                   \
GA_24_15173_CGATGT.co.gz                                                   \
GA_24_15173_GTTCAC.co.gz                                                   \
GA_24_15173_TCTTAG.co.gz                                                   \
GA_24_15173_TGCAGT.co.gz                                                   \
GA_24c_15171_AGCTTG.co.gz                                                  \
GA_24c_15171_GCCAAG.co.gz                                                  \
GA_24c_15171_TGACCA.co.gz                                                  \
GA_24c_15171_TTAGGC.co.gz                                                  \
GA_48_15174_CTTGTA.co.gz                                                   \
GA_48_15174_GCTGAA.co.gz                                                   \
GA_48_15174_GGCTAC.co.gz                                                   \
GA_48_15174_TAGCTT.co.gz                                                   \
GA_48c_15172_ACAGTG.co.gz                                                  \
GA_48c_15172_ACTTGA.co.gz                                                  \
GA_48c_15172_ATGTCT.co.gz                                                  \
GA_48c_15172_GATCAG.co.gz                                                  \
GA_48c_15172_TCTACA.co.gz                                                  \
GT_24_15432_CGATGT.co.gz                                                   \
GT_24_15432_GTTCAC.co.gz                                                   \
GT_24_15432_TCTTAG.co.gz                                                   \
GT_24_15432_TGCAGT.co.gz                                                   \
GT_24c_15430_AGCTTG.co.gz                                                  \
GT_24c_15430_GCCAAG.co.gz                                                  \
GT_24c_15430_TGACCA.co.gz                                                  \
GT_24c_15430_TTAGGC.co.gz                                                  \
GT_48_15433_CTTGTA.co.gz                                                   \
GT_48_15433_GCTGAA.co.gz                                                   \
GT_48_15433_GGCTAC.co.gz                                                   \
GT_48_15433_TAGCTT.co.gz                                                   \
GT_48c_15431_ACAGTG.co.gz                                                  \
GT_48c_15431_ACTTGA.co.gz                                                  \
GT_48c_15431_ATGTCT.co.gz                                                  \
GT_48c_15431_GATCAG.co.gz                                                  \
CA_24_15639_CGATGT.co.gz                                                   \
CA_24_15639_GTTCAC.co.gz                                                   \
CA_24_15639_GTTCAC.co.gz                                                   \
CA_24_15639_TCTTAG.co.gz                                                   \
CA_24_15639_TGCAGT.co.gz                                                   \
CA_24c_15637_AGCTTG.co.gz                                                  \
CA_24c_15637_GCCAAG.co.gz                                                  \
CA_24c_15637_TGACCA.co.gz                                                  \
CA_24c_15637_TTAGGC.co.gz                                                  \
CA_48_15640_CTTGTA.co.gz                                                   \
CA_48_15640_GCTGAA.co.gz                                                   \
CA_48_15640_GGCTAC.co.gz                                                   \
CA_48_15640_TAGCTT.co.gz                                                   \
CA_48c_15638_ACAGTG.co.gz                                                  \
CA_48c_15638_ACTTGA.co.gz                                                  \
CA_48c_15638_ATGTCT.co.gz                                                  \
CA_48c_15638_GATCAG.co.gz                                                  \
24_13073_GCCAAG.co.gz                                                      \
24_13073_GTTCAC.co.gz                                                      \
24_13073_TCTTAG.co.gz                                                      \
24_13073_TGCAGT.co.gz                                                      \
48_13074_ATGTCT.co.gz                                                      \
48_13074_GCTGAA.co.gz                                                      \
48_13074_TAGGAC.co.gz                                                      \
48_13074_TCTACA.co.gz                                                      \
con_13072_AGCTTG.co.gz                                                     \
con_13072_CGATGT.co.gz                                                     \
con_13072_CTGGAT.co.gz                                                     \
con_13072_TTAGGC.co.gz                                                     \
con_13072_TTAGGC.co.gz                                                     \
GTLa_24_15479_CGATGT.co.gz                                                 \
GTLa_24_15479_GTTCAC.co.gz                                                 \
GTLa_24_15479_TCTTAG.co.gz                                                 \
GTLa_24_15479_TGCAGT.co.gz                                                 \
GTLa_24c_15477_AGCTTG.co.gz                                                \
GTLa_24c_15477_GCCAAG.co.gz                                                \
GTLa_24c_15477_TGACCA.co.gz                                                \
GTLa_24c_15477_TTAGGC.co.gz                                                \
GTLa_48_15480_CTTGTA.co.gz                                                 \
GTLa_48_15480_GCTGAA.co.gz                                                 \
GTLa_48_15480_GGCTAC.co.gz                                                 \
GTLa_48_15480_TAGCTT.co.gz                                                 \
GTLa_48c_15478_ACAGTG.co.gz                                                \
GTLa_48c_15478_ACTTGA.co.gz                                                \
GTLa_48c_15478_ATGTCT.co.gz                                                \
GTLa_48c_15478_GATCAG.co.gz                                                \
CAla_24_15643_CGATGT.co.gz                                                 \
CAla_24_15643_GTTCAC.co.gz                                                 \
CAla_24_15643_TCTTAG.co.gz                                                 \
CAla_24_15643_TGCAGT.co.gz                                                 \
CAla_24c_15641_AGCTTG.co.gz                                                \
CAla_24c_15641_GCCAAG.co.gz                                                \
CAla_24c_15641_TGACCA.co.gz                                                \
CAla_24c_15641_TTAGGC.co.gz                                                \
CAla_48_15644_CTTGTA.co.gz                                                 \
CAla_48_15644_GCTGAA.co.gz                                                 \
CAla_48_15644_GGCTAC.co.gz                                                 \
CAla_48_15644_TAGCTT.co.gz                                                 \
CAla_48c_15642_ACAGTG.co.gz                                                \
CAla_48c_15642_ACTTGA.co.gz                                                \
CAla_48c_15642_ATGTCT.co.gz                                                \
CAla_48c_15642_GATCAG.co.gz                                                \
Gala_24_15624_CGATGT.co.gz                                                 \
Gala_24_15624_GTTCAC.co.gz                                                 \
Gala_24_15624_TCTTAG.co.gz                                                 \
Gala_24_15624_TGCAGT.co.gz                                                 \
Gala_24c_15622_AGCTTG.co.gz                                                \
Gala_24c_15622_GCCAAG.co.gz                                                \
Gala_24c_15622_TGACCA.co.gz                                                \
Gala_24c_15622_TTAGGC.co.gz                                                \
Gala_48_15625_CTTGTA.co.gz                                                 \
Gala_48_15625_GCTGAA.co.gz                                                 \
Gala_48_15625_GGCTAC.co.gz                                                 \
Gala_48_15625_TAGCTT.co.gz                                                 \
Gala_48c_15623_ACAGTG.co.gz                                                \
Gala_48c_15623_ACTTGA.co.gz                                                \
Gala_48c_15623_ATGTCT.co.gz                                                \
Gala_48c_15623_GATCAG.co.gz                                                \
Gala_48c_15623_GATCAG.co.gz                                                \
GF6_10536_ACAGTG.co.gz                                                     \
GF6_10536_ACTTGA.co.gz                                                     \
GF6_10536_ATCACG.co.gz                                                     \
GF6_10536_CAGATC.co.gz                                                     \
GF6_10536_CAGTTC.co.gz                                                     \
GF6_10536_CGATGT.co.gz                                                     \
GF6_10536_CTTGTA.co.gz                                                     \
GF6_10536_GATCAG.co.gz                                                     \
GF6_10536_GATCTG.co.gz                                                     \
GF6_10536_GCCAAT.co.gz                                                     \
GF6_10536_GGCTAC.co.gz                                                     \
GF6_10536_TAGCTT.co.gz                                                     \
GF6_10536_TGACCA.co.gz                                                     \
GF6_10536_TTAGGC.co.gz


all: $(TARGETS)

%.pps: %_read1.fastq.gz %_read2.fastq.gz
	python preprocess.py $^ > $@

%.stc: %.pps
	cut -f1 $< | starcode -d2 --print-clusters > $@

%.co.gz: %.pps %.stc
	python count.py $^ | gzip > $@ && rm $^

clean:
	rm -rf *.pps *.co.gz
