#!/usr/bin/bash
# -*- coding:utf-8 -*-

python make_features.py ../mapping/black.lst GA_24_15173_CGATGT.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_24_15173_GTTCAC.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_24_15173_TCTTAG.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_24_15173_TGCAGT.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_24c_15171_AGCTTG.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_24c_15171_GCCAAG.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_24c_15171_TGACCA.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_24c_15171_TTAGGC.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_48_15174_CTTGTA.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_48_15174_GCTGAA.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_48c_15172_ACAGTG.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_48c_15172_ACTTGA.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_48c_15172_ATGTCT.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_48c_15172_GATCAG.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GAn_la_24_20465_AGCTTG.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GAn_la_24_20465_CGATGT.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GAn_la_24_20465_TCTTAG.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GAn_la_24_20465_TGCAGT.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GAn_la_48_20466_ATGTCT.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GAn_la_48_20466_GCCAAG.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GAn_la_48_20466_GTTCAC.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GAn_la_48_20466_TTAGGC.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GAn_la_c_20464_CTGGAT.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GAn_la_c_20464_GCTGAA.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GAn_la_c_20464_TAGGAC.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GAn_la_c_20464_TCTACA.co.gz ../mapping/GA1.ins ../mapping/GA2.ins

python make_features.py ../mapping/black.lst CA_24_15639_CGATGT.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_24_15639_GTTCAC.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_24_15639_TCTTAG.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_24_15639_TGCAGT.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_24c_15637_AGCTTG.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_24c_15637_GCCAAG.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_24c_15637_TGACCA.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_24c_15637_TTAGGC.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_48_15640_CTTGTA.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_48_15640_GGCTAC.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_48c_15638_ACTTGA.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_48c_15638_ATGTCT.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_48c_15638_GATCAG.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_24_15643_CGATGT.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_24_15643_GTTCAC.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_24_15643_TCTTAG.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_24_15643_TGCAGT.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_24c_15641_AGCTTG.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_24c_15641_GCCAAG.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_24c_15641_TGACCA.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_24c_15641_TTAGGC.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_48_15644_CTTGTA.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_48_15644_GCTGAA.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_48_15644_GGCTAC.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_48_15644_TAGCTT.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_48c_15642_ACAGTG.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_48c_15642_ACTTGA.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_48c_15642_ATGTCT.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_48c_15642_GATCAG.co.gz ../mapping/CA1.ins ../mapping/CA2.ins

python make_features.py ../mapping/black.lst 24_13073_GCCAAG.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst 24_13073_GTTCAC.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst 24_13073_TCTTAG.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst 24_13073_TGCAGT.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst 48_13074_ATGTCT.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst 48_13074_GCTGAA.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst 48_13074_TAGGAC.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst 48_13074_TCTACA.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst con_13072_AGCTTG.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst con_13072_CGATGT.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst con_13072_CTGGAT.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst con_13072_TTAGGC.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_24_13508_AGCTTG.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_24_13508_CGATGT.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_24_13508_TCTTAG.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_24_13508_TGCAGT.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_48_13509_ATGTCT.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_48_13509_GCCAAG.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_48_13509_GTTCAC.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_48_13509_TTAGGC.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_c_13507_CTGGAT.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_c_13507_GCTGAA.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_c_13507_TAGGAC.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_c_13507_TCTACA.co.gz ../mapping/CT1.ins ../mapping/CT2.ins

python make_features.py ../mapping/black.lst GTLa_24_15479_CGATGT.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GTLa_24_15479_GTTCAC.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GTLa_24_15479_TCTTAG.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GTLa_24_15479_TGCAGT.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GTLa_24c_15477_AGCTTG.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GTLa_24c_15477_GCCAAG.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GTLa_24c_15477_TGACCA.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GTLa_24c_15477_TTAGGC.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GTLa_48_15480_CTTGTA.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GTLa_48_15480_GCTGAA.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GTLa_48_15480_GGCTAC.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GTLa_48_15480_TAGCTT.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GTLa_48c_15478_ACAGTG.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GTLa_48c_15478_ACTTGA.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GTLa_48c_15478_ATGTCT.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GTLa_48c_15478_GATCAG.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GT_24_15432_CGATGT.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GT_24_15432_GTTCAC.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
# ---->  The one below is fairly biased.
python make_features.py ../mapping/black.lst GT_24_15432_TCTTAG.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GT_24_15432_TGCAGT.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GT_24c_15430_AGCTTG.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GT_24c_15430_GCCAAG.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GT_24c_15430_TGACCA.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GT_24c_15430_TTAGGC.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
#python make_features.py ../mapping/black.lst GT_48_15433_CTTGTA.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
#python make_features.py ../mapping/black.lst GT_48_15433_GGCTAC.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
#python make_features.py ../mapping/black.lst GT_48_15433_TAGCTT.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GT_48c_15431_ACAGTG.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GT_48c_15431_ACTTGA.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GT_48c_15431_ATGTCT.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
python make_features.py ../mapping/black.lst GT_48c_15431_GATCAG.co.gz ../mapping/GT1.ins ../mapping/GT2.ins
