#!/usr/bin/bash
# -*- coding:utf-8 -*-

python make_features.py ../mapping/black.lst GA_24_15173_CGATGT.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_24_15173_GTTCAC.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_24_15173_TCTTAG.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_24_15173_TGCAGT.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_24c_15171_AGCTTG.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_24c_15171_GCCAAG.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_24c_15171_TGACCA.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_24c_15171_TTAGGC.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_48_15174_CTTGTA.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_48_15174_GCTGAA.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_48c_15172_ACAGTG.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_48c_15172_ACTTGA.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_48c_15172_ATGTCT.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst GA_48c_15172_GATCAG.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
#python make_features.py ../mapping/black.lst GA_48c_15172_TCTACA.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst Gala_24_15624_CGATGT.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst Gala_24_15624_GTTCAC.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst Gala_24_15624_TCTTAG.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst Gala_24_15624_TGCAGT.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst Gala_24c_15622_AGCTTG.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
#python make_features.py ../mapping/black.lst Gala_24c_15622_GCCAAG.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst Gala_24c_15622_TGACCA.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst Gala_24c_15622_TTAGGC.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst Gala_48_15625_CTTGTA.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst Gala_48_15625_GCTGAA.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst Gala_48_15625_GGCTAC.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst Gala_48_15625_TAGCTT.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst Gala_48c_15623_ACAGTG.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
#python make_features.py ../mapping/black.lst Gala_48c_15623_ACTTGA.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
python make_features.py ../mapping/black.lst Gala_48c_15623_ATGTCT.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
#python make_features.py ../mapping/black.lst Gala_48c_15623_GATCAG.co.gz ../mapping/GA1.ins ../mapping/GA2.ins
#python make_features.py ../mapping/black.lst Gala_48c_15623_GATCAG.co.gz ../mapping/GA1.ins ../mapping/GA2.ins

python make_features.py ../mapping/black.lst CA_24_15639_CGATGT.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_24_15639_GTTCAC.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_24_15639_TCTTAG.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_24_15639_TGCAGT.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_24c_15637_AGCTTG.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_24c_15637_GCCAAG.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_24c_15637_TGACCA.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_24c_15637_TTAGGC.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_48_15640_CTTGTA.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_48_15640_GGCTAC.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
#python make_features.py ../mapping/black.lst CA_48c_15638_ACAGTG.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_48c_15638_ACTTGA.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_48c_15638_ATGTCT.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CA_48c_15638_GATCAG.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_24_15643_CGATGT.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_24_15643_GTTCAC.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_24_15643_TCTTAG.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_24_15643_TGCAGT.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_24c_15641_AGCTTG.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_24c_15641_GCCAAG.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_24c_15641_TGACCA.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_24c_15641_TTAGGC.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_48_15644_CTTGTA.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_48_15644_GCTGAA.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_48_15644_GGCTAC.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_48_15644_TAGCTT.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_48c_15642_ACAGTG.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_48c_15642_ACTTGA.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_48c_15642_ATGTCT.co.gz ../mapping/CA1.ins ../mapping/CA2.ins
python make_features.py ../mapping/black.lst CAla_48c_15642_GATCAG.co.gz ../mapping/CA1.ins ../mapping/CA2.ins

python make_features.py ../mapping/black.lst 24_13073_GCCAAG.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst 24_13073_GTTCAC.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst 24_13073_TCTTAG.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst 24_13073_TGCAGT.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst 48_13074_ATGTCT.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst 48_13074_GCTGAA.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst 48_13074_TAGGAC.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst 48_13074_TCTACA.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst con_13072_AGCTTG.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst con_13072_CGATGT.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst con_13072_CTGGAT.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst con_13072_TTAGGC.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_24_13508_AGCTTG.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_24_13508_CGATGT.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_24_13508_TCTTAG.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_24_13508_TGCAGT.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_48_13509_ATGTCT.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_48_13509_GCCAAG.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_48_13509_GTTCAC.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_48_13509_TTAGGC.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_c_13507_CTGGAT.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_c_13507_GCTGAA.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_c_13507_TAGGAC.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
python make_features.py ../mapping/black.lst LA_c_13507_TCTACA.co.gz ../mapping/CT1.ins ../mapping/CT2.ins
